### ISSUE TITLE
Gathering of smart contracts creation is incomplete

### ISSUE THREAD

**Issue by jack695** [Longferret/smart_contract_tax#1]
Hi, 

I've just noticed that the way you collect smart contracts might not capture all smart contracts. 

Considering the code you've written, it looks like you are only looking at **external transactions** creating smart contracts.

https://github.com/Longferret/smart_contract_tax/blob/711d5dc707f6a6e9a1722c43cb143e41c5b33ad7/code/gather_contract/gather_contract.py#L103

However, **internal calls** can also create smart contracts. Let's say that Bob sends a transaction to a deployed contract's function (e.g. Gnosis Factory) which is in charge to create a contract. As the destination of the external transaction is not the null address, you won't detect this new contract.

I recommend you to investigate the API to generate traces in order to catch all smart contracts deployed. 

https://docs.alchemy.com/reference/what-are-evm-traces

**Comment by Longferret** [comment]
Yes I've seen on forums that this type of contract creation is harder to spot.
Thank you for the website with the explanation.
What I will do next :
1.  Gather contracts created by internal calls
2.  Maybe list all contracts that are accessed (but that will require me to have a real database, not just folders)

**Comment by Longferret** [comment]
The scipt is modified and now also analyze the trace of each transaction to spot contract creation by internal calls

**Comment by Longferret** [comment]
The script is modified and now also analyze the trace of each transaction to spot contract creation by internal calls
